name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x] 

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: ./cs476.project.UI/package-lock.json
    - name: Install Dependencies
      run: pnpm install
      working-directory: ./cs476.project.UI

    - name: Lint Check
      run: pnpm run lint
      working-directory: ./cs476.project.UI

    - name: UI building
      run: pnpm run build
      working-directory: ./cs476.project.UI
